name: Run E2E Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          run-install: false
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v7
        env:
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api.vercel.app"
        with:
          build: npm run build
          start: npm start
